name: test curl 2

on:
  workflow_dispatch:
    # inputs:
    #     job_id:
    #       required: true
    #     wf_id:
    #       required: true

jobs:
  curl_test2:
    runs-on: ubuntu-latest
  
    steps:
    - run: |
        pwd
        ls 
        # ${{ secrets.MY_TOKEN }}
        # ${{ github.event.inputs.job_id }}
        # ${{ github.event.inputs.wf_id }}
        curl -X GET "https://api.github.com/repos/nikhildave-96/java-selenium-cucumber-BDD/actions/jobs/40783882806/logs" --header "Accept: application/vnd.github+json" --header "Authorization: Bearer ${{ secrets.MY_TOKEN }}" -L -o test456.txt
        pwd
        ls
        
